"""Added storage_path column

Revision ID: c9451d62d432
Revises: 11b1b67eff0e
Create Date: 2026-09-24 18:51:35.011989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9451d62d432'
down_revision: Union[str, None] = '11b1b67eff0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('storage_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'storage_path')
    # ### end Alembic commands ###
